on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

name: run meituan
jobs:
  meituan:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          ref: main
      - name: meituan
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./mtV4.py
    env:
      MEITUAN_COOKIE: ${{secrets.MEITUAN_COOKIE}}
      PUSH_KEY: ${{secrets.PUSH_KEY}}
      PUSH_URL: ${{secrets.PUSH_URL}}