on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

name: run kuake
jobs:
  kuake:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          ref: main
      - name: kuake
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./kuake.py
    env:
      COOKIE_QUARK: ${{secrets.COOKIE_QUARK}}