on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

name: run yundong
jobs:
  aliyun:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          ref: main
      - name: aliyun
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./aliyun.py
    env:
      ALI_REFRESH_TOKEN: ${{secrets.ALI_REFRESH_TOKEN}}