jobs:
  tieba:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: tieba
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
          architecture: 'x64'
      - run: pip install -r ./requirements.txt && python ./tieba.py

    env:
      TIEBACK: ${{secrets.TIEBACK}}
      PUSH_KEY: ${{secrets.PUSH_KEY}}
      PUSH_URL: ${{secrets.PUSH_URL}}

name: run tieba
on:
  schedule:
  - cron:  '20 3 * * *'
  workflow_dispatch:


