on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

name: run yundong
jobs:
  meituan:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          ref: main
      - name: xiaomiyundong
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./xiaomiyundong.py
    env:
      MISPORT: ${{secrets.MISPORT}}